src/accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
path("signup/", SignUpView.as_view(), name="signup"),
]

src/blog/urls.py
from django.urls import path

from .views import BlogListView, HomePageView, BlogDetailView, CVPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("blog/", BlogListView.as_view(), name="blog"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("cv/", CVPageView.as_view(), name="cv")
]

src/myBlog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls"))
]

src/pages/urls.py
from django.urls import path
from .views import AboutPageView, HomePageView


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about")
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/blog/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

src/pages/models.py
from django.db import models

# Create your models here.

src/accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = 'registration/signup.html'

src/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView, DetailView
from .models import Post

class HomePageView(TemplateView):
    template_name = "home.html"

class BlogListView(ListView):
    model = Post
    template_name = "blog.html"

class BlogDetailView(DetailView):
    model = Post
    template_name = "post_detail.html"

class CVPageView(TemplateView):
    template_name = "cv.html"

src/pages/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = "home.html"

class AboutPageView(TemplateView):
    template_name = "about.html"

src/blog/templates/base.html
{% load static %}

<html>
    <head>
    <title>Django blog</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet"> 
    </head>
    <body>
        <header>
            <ul class="menu">
                <li><a href="{% url 'home' %}">Accueil</a></li>
                
                {% if user.is_authenticated %}
                    <li><a  href="{% url 'blog' %}">Django blog</a></li>
                    <li><a href="{% url 'cv' %}">Qui suis-je ?</a></li>
                    <li><h2>Bonsoir {{ user.username }}, je suis sûr que tu es ici grâce à mon OnlyFan</h1></li>
                    <li><a href="{% url 'logout' %}">Déconnexion</a></li>                
                {% else %}
                        <figure>
                            <a href="{% url 'login' %}"><img src="{% static 'img/wink.png' %}" alt="picture wink"></a>
                            <figcaption class="accueil">Ooooh mais tu n'es pas connecté mon bichon ! Viens vite et profite de mon contenu très très HOT en cliquant sur mon visage.</figcaption>
                        </figure>
                {% endif %}
            </ul>

            <!--<h1 ><a href="{% url 'home' %}">Accueil</a></h1>
            <h1><a  href="{% url 'blog' %}">Django blog</a></h1>
            <div class="logout">
                {% if user.is_authenticated %}
                    <p>Bonsoir {{ user.username }}, je suis sûr que tu es ici grâce à mon OnlyFan</p>
                    <h2><a href="{% url 'logout' %}">Déconnexion</a></h2>
                {% else %}
                    <figure>
                        <a href="{% url 'login' %}"><img src="{% static 'img/wink.png' %}" alt="picture wink"></a>
                        <figcaption class="accueil">Ooooh mais tu n'es pas connecté mon bichon ! Viens vite et profite de mon contenu très très HOT en cliquant sur mon visage.</figcaption>
                    </figure>   
                {% endif %}
            </div> -->
        </header>
        <div>
        {% block content %}
        {% endblock content %}
        </div>
        <footer><a href="{% url 'signup' %}"> S'inscrire</a></footer>
    </body>
</html>

src/blog/templates/blog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% for post in post_list %}
<div class="post-entry">
    <h2 class="menu"><a href="">{{ post.title }}</a></h2>
    <p>{{ post.body }}</p>
</div>
{% endfor %}
{% endblock content %}

src/blog/templates/cv.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container">
    <h1>Le beau CV numero UNO de Don Jean Gilbiere</h1>
</div>

    <div class="cv-container">
        <div class="left-column">

            <h1>Regardez comme je suis gai</h1>
            <img src="{% static 'img/profil_décontract.png' %}" alt="photo de profil" width="300" height="400">
        </div>
        <div class="right-column">
            <h1>Mes diplômes</h1>
                <ul>
                    <li>Best Troll World</li>
                    <li>Procrastineur de l'année</li>
                    <li>Meilleur carrière dev branleur d'ATOS</li>
                </ul>
            <h1>Mes compétences</h1>
                <ul>
                    <li>Être capable de porter à bout de bras Flav et Flo sur LoL, ces deux bronzes 5 du dimanche.</li>
                    <li>Je suis capable de me souvenir de toute la vie de Flavien et la raconter de façon très précise.</li>
                    <li>Tolérant, je ne pas suis islamophobe car j'ai un ami avec une barbe d'islamiste</li>
                </ul>
            <h1>Mes activités</h1>
                <ul>
                    <li>Travail</li>
                    <li>Famille</li>
                    <li>Patrie</li>
                </ul>
            <div class="header">
            <h1> Don Jean Gilbiere - Développeur en polystyrène du dimanche</h1>
            </div>
            <div class="content">
            
            </div>
        </div>
    </div>

    {% endblock content %}

src/blog/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div>
    <img class="img" src="{% static 'img/pinky_duck.png' %}" alt="photo duck" width="10%" height="15%">
</div>

<h1 class="accueil">Ma page d'accueil pour les coquins comme toi.</h1>
<img src="{% static 'img/shh.png' %}" alt="Photo shh">
<ul>
    {% for post in post_list %}
    <li>{{ post.text }}</li>
    {% endfor %}
</ul>
{% endblock content %}

src/blog/templates/post_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="post-entry">
    <h2>{{ post.title }}</h2>
    <p>{{ post.body}}</p>
</div>
{% endblock content %}

src/pages/templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

src/pages/templates/base.html
<header>
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'about' %}">About</a>
</header>

{% block content %} {% endblock content %}

src/pages/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Homepage test</h1>
{% endblock content %}